.PHONY: build pub clean

build:
	npm run build
	rm -rf build
	mkdir build
	cp Dockerfile build/Dockerfile
	cp deploy.sh build/deploy.sh
	cp package.json build/package.json
	cp -R dist build/dist
	rm -rf dist
	yarn --cwd ./build install --production
